name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4  # Checkout the repo

      - uses: vn7n24fzkq/github-profile-summary-cards@release  # Action to generate the cards
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}  # Use your GitHub token stored as a secret
        with:
          USERNAME: Izaacapp  # Your GitHub username
          BRANCH_NAME: "main"  # This is the branch to push the cards to
          UTC_OFFSET: 8  # Your time zone offset (change if necessary)
          EXCLUDE: ""  # Any languages to exclude
          AUTO_PUSH: true  # Automatically push the changes
